FROM ubuntu:16.04

RUN apt-get update && \
  apt-get install -y software-properties-common && \
  add-apt-repository -y ppa:inkscape.dev/stable && \
  apt-get update -y && \
  apt-get install -y inkscape
